apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-app
  namespace: exam-samuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: php-logger
          image: php-logger:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: logger-config
            - secretRef:
                name: logger-secret
          volumeMounts:
            - name: logger-storage
              mountPath: /logs
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: logger-storage
          persistentVolumeClaim:
            claimName: logger-pvc
