apiVersion: v1
kind: PersistentVolume
metadata:
  name: logger-pv
  namespace: exam-samuel
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/logger"
